packages:
  - docs
  - playground/cms
  - playground

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - sharp

patchedDependencies:
  '@nuxt/ui-pro': patches/@nuxt__ui-pro.patch

