packages:
  - docs
  - playground/cms
  - playground

ignoreWorkspaceRootCheck: true

overrides:
  "@nuxt/schema": "4.5.0"
  "@nuxtjs/sanity": "link:."
  nuxt-component-meta: "0.17.2"

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: false
