// Type declarations for virtual modules generated by this module
// These stubs are used for type checking source files before Nuxt app preparation

declare module '#build/sanity-visual-editing-refresh.mjs' {
  import type { SanityVisualEditingOnSuspiciousStega, SanityVisualEditingRefreshHandler } from '@nuxtjs/sanity'

  export const sanityVisualEditingRefresh: SanityVisualEditingRefreshHandler | undefined
  export const sanityVisualEditingOnSuspiciousStega: SanityVisualEditingOnSuspiciousStega | undefined
}

// Remove once @sanity/visual-editing-standalone types `./styles.css`
// https://github.com/sanity-io/visual-editing/pull/3630
declare module '@sanity/visual-editing-standalone/styles.css'
