// Type declarations for virtual modules generated by this module
// These stubs are used for type checking source files before Nuxt app preparation

declare module '#build/sanity-visual-editing-refresh.mjs' {
  import type { SanityVisualEditingRefreshHandler } from '@nuxtjs/sanity'

  export const sanityVisualEditingRefresh: SanityVisualEditingRefreshHandler | undefined
}
