/* @vitest-environment node */
import { setup } from '@nuxt/test-utils/e2e'
import { describe, expect, it } from 'vitest'
import { readFile } from 'node:fs/promises'
import { resolve } from 'pathe'

const rootDir = resolve(process.cwd(), 'playground')

await setup({
  server: true,
  rootDir,
  nuxtConfig: {
    sanity: {
      projectId: 'j1o4tmjp',
      typegen: {
        enabled: true,
        schemaTypesPath: './cms/schemaTypes/index.ts',
        // Keep the scan small for this test
        queryPaths: ['./pages/movie/[slug].vue'],
      },
    },
  },
})

describe('sanity typegen (nuxt integration)', () => {
  it('generates a type template in .nuxt', async () => {
    const typesFile = resolve(rootDir, '.nuxt/types/sanity-typegen.d.ts')
    const content = await readFile(typesFile, 'utf8')

    expect(content).toContain('// Generated by @nuxtjs/sanity')
    expect(content).toContain('declare module "@sanity/client"')
    expect(content).toContain('interface SanityQueries')
  })
})
