name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [22]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          runtime: node@${{ matrix.node }}
          cache: true
          require-lockfile: true

      - name: 🚧 Set up project
        run: pnpm dev:prepare

      - name: 💪 Test types
        run: pnpm test:types

      - name: 🛠 Build project
        run: pnpm build

      - name: 🛝 Build playground
        run: pnpm dev:build

      - name: 🎨 Build studio
        run: pnpm studio:build

      - name: 💪 Test built types
        run: pnpm test:types

      - name: 🧪 Test project
        run: pnpm test

      - name: ⚙️ Check engine ranges
        run: pnpm installed-check --no-workspaces -d

      - name: 🟩 Coverage
        if: matrix.os != 'windows-latest'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          require-lockfile: true

      - name: 🚧 Set up project
        run: pnpm dev:prepare

      - name: 🛠 Build project
        run: pnpm build

      - name: 🌃 publish nightly release
        run: pnpm pkg-pr-new publish --compact --pnpm
